services:
  db:
    image: postgres:16
    container_name: trading_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: StockTrader
      POSTGRES_PASSWORD: P@ssw0rd!
      POSTGRES_DB: TradingDB
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: